---
- hosts: all
  become: true
  pre_tasks:
    - name: Set hostname in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.0\.1.*'
        line: "127.0.0.1   localhost {{ inventory_hostname }} {{ ansible_hostname }}"
        state: present
    - name: Set hostname in /etc/hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
        use: debian
  roles:
    - tbauriedel.hosts